#EXTM3U


#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://mibitivi.xyz/sc/lic.php?tekon=x13x101x13x&a=useesports2
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", US 1 SPORTZ
https://mibitivi.xyz/sc/play.mpd?tekon=x13x101x13x&channel=useesport

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://mibitivi.xyz/sc/lic.php?tekon=x13x101x13x&a=useesports2
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", US 2 SPORTZ
https://mibitivi.xyz/sc/play.mpd?tekon=x13x101x13x&channel=useesports2

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", SP 1 SPORTZ
https://bcovlive-a.akamaihd.net/99545824f51f4c1592b35314c6ece3b0/ap-northeast-1/6271486521001/profile_1/chunklist.m3u8
https://rebrand.ly/3t0uu98

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", SP 2 SPORTZ
https://bcovlive-a.akamaihd.net/48eee16919834d3b97df1082a649bcfa/ap-northeast-1/6271486521001/profile_1/chunklist.m3u8
https://rebrand.ly/ch5691r

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", GP SPORTZ
https://dornatoken.secure.footprint.net/token=nva=1652543766~dirs=2~ip=0.0.0.0~data=H4Z6YoGbmxZQ4Jxk0%252BKIalln%252FPQ6GYP8qixsCgOwqkzjAqBM9u9MM%252FAD01rHZFKi~token=0603c579b0484de7a4caf/hls/ipfmix/3.m3u8?start=0&|referer=https://bangkebola.blogspot.com/p/if-p2pml.html?m=1

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", GP SPORTZ
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", CM 1 SPORTZ
https://akumaymd.000webhostapp.com/master-6.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", CM 2 SPORTZ
https://akumaymd.000webhostapp.com/master-7.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", CM 3 SPORTZ
https://akumaymd.000webhostapp.com/master-8.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", OCH SPORTZ
https://akumaymd.000webhostapp.com/master-18.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", IN D SPORTZ
https://akumaymd.000webhostapp.com/master.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", AR SPORTZ
http://urtv.cc:80/454781209544/431009674535/6707

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", AS 5 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6793

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", AS 4 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6712

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", AS 3 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6711

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", AS 2 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6710

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", AS 1 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6708

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", SP 1 SPORTZ
http://mvu03.wanicelife.com:8880/SFL143499/N88PH236/2942
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", SP 2 SPORTZ
http://urtv.cc:80/449042/449042/9034

#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", T SPORTZ 1 HD
http://urtv.cc:80/449042/449042/6610
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", T SPORTZ 2 HD
http://urtv.cc:80/449042/449042/6611
#EXTINF:-1 tvg-logo="https://i.ibb.co/MSf6wFs/w.png", T SPORTZ 2 HD
http://urtv.cc:80/449042/449042/6612

