#EXTM3U

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", SP 1 SPORTZ
https://bcovlive-a.akamaihd.net/99545824f51f4c1592b35314c6ece3b0/ap-northeast-1/6271486521001/profile_1/chunklist.m3u8

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", SP 2 SPORTZ
https://bcovlive-a.akamaihd.net/48eee16919834d3b97df1082a649bcfa/ap-northeast-1/6271486521001/profile_1/chunklist.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", ID N SPORTZ
https://seulangatv.com/vd/get.m3u8?id=205|User-agent=SeulangaTV
https://www.seulangatv.xyz/ns/vidio/indosiar.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", ID 1 SPORTZ
https://seulangatv.xyz/bola/get_live.m3u8?id=pialapresiden1|User-agent=SeulangaTV
https://www.seulangatv.xyz/ns/vidio/indosiar.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", ID 2 SPORTZ
https://seulangatv.xyz/bola/get_live.m3u8?id=pialapresiden2|User-agent=SeulangaTV
https://www.seulangatv.xyz/ns/vidio/indosiar.m3u8

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://seulangatv.com/DRMurl/useetv.key?id=useesport
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", US 1 SPORTZ
https://seulangatv.com/useeTV/mpd/get.mpd?id=useesport|User-agent=punya=SeulangaTV
http://51.79.251.180:2082/fadilah/fadilah/2551

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://seulangatv.com/DRMurl/useetv.key?id=useesports2
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", US 2 SPORTZ
https://seulangatv.com/useeTV/mpd/get.mpd?id=useesports2|User-agent=punya=SeulangaTV
http://51.79.251.180:2082/fadilah/fadilah/2552

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", CM 1 SPORTZ
https://www.seulangatv.xyz/ns/vidio/champ1.m3u8|User-agent=Delvik

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", CM 2 SPORTZ
https://www.seulangatv.xyz/ns/vidio/champ2.m3u8|User-agent=Delvik

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", CM 3 SPORTZ
https://www.seulangatv.xyz/ns/vidio/champ3.m3u8|User-agent=Delvik

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", GP SPORTZ
http://kunyak.my.id/soklah/spotv.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", OCH SPORTZ
https://www.seulangatv.xyz/ns/vidio/ochannel.m3u8|User-agent=SeulangaTV

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AR SPORTZ
http://urtv.cc:80/454781209544/431009674535/6707

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 5 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6793

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 4 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6712

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 3 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6711

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 2 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6710

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 1 SPORTZ
http://urtv.cc:80/454781209544/431009674535/6708

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", SP 1 SPORTZ
http://mvu03.wanicelife.com:8880/SFL143499/N88PH236/2942
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", SP 2 SPORTZ
http://urtv.cc:80/449042/449042/9034

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", T SPORTZ 1 HD
http://urtv.cc:80/449042/449042/6610
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", T SPORTZ 2 HD
http://urtv.cc:80/449042/449042/6611
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", T SPORTZ 2 HD
http://urtv.cc:80/449042/449042/6612

