#EXTM3U

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", SP 1 SPORTZ
https://bcovlive-a.akamaihd.net/99545824f51f4c1592b35314c6ece3b0/ap-northeast-1/6271486521001/profile_1/chunklist.m3u8

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", SP 2 SPORTZ
https://bcovlive-a.akamaihd.net/48eee16919834d3b97df1082a649bcfa/ap-northeast-1/6271486521001/profile_1/chunklist.m3u8

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", ID N SPORTZ
https://seulangatv.com/vd/get.m3u8?id=205|User-agent=SeulangaTV

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", ID 1 SPORTZ
https://seulangatv.xyz/bola/get_live.m3u8?id=pialapresiden1|User-agent=SeulangaTV

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", ID 2 SPORTZ
https://seulangatv.xyz/bola/get_live.m3u8?id=pialapresiden2|User-agent=SeulangaTV

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", GL SPORTZ
https://tvn10.xyz/vidio/chg.m3u8|User-agent=punya=SeulangaTV

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://seulangatv.com/DRMurl/useetv.key?id=useesport
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", US 1 SPORTZ
https://seulangatv.com/useeTV/mpd/get.mpd?id=useesport|User-agent=punya=SeulangaTV

#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
#KODIPROP:inputstream.adaptive.license_key=https://seulangatv.com/DRMurl/useetv.key?id=useesports2
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", US 2 SPORTZ
https://seulangatv.com/useeTV/mpd/get.mpd?id=useesports2|User-agent=punya=SeulangaTV

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", OCH SPORTZ
https://tvn10.xyz/vidio/och.m3u8|User-agent=punya=SeulangaTV

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", CM 1 SPORTZ
https://www.seulangatv.xyz/ns/vidio/champ1.m3u8|User-agent=Delvik

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", CM 2 SPORTZ
https://www.seulangatv.xyz/ns/vidio/champ2.m3u8|User-agent=Delvik

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", CM 3 SPORTZ
https://www.seulangatv.xyz/ns/vidio/champ3.m3u8|User-agent=Delvik

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AR SPORTZ
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/157485

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 5 SPORTZ
https://netwrk.ru.com/cdn/premium43/chunks.m3u8|referer=https://player.licenses4.me

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 4 SPORTZ
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/157558

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 3 SPORTZ
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/157557

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 2 SPORTZ
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/157556

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", AS 1 SPORTZ
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/146068

#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", T SPORTZ 1 HD
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/270
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", T SPORTZ 2 HD
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/273
#EXTINF:-1 tvg-logo="https://i.ibb.co/fCLdDp7/l.png", T SPORTZ 3 HD
http://quality-restream.com:8080/linuxapp2021/M3jc66jD9UCnpK9v/271

